##
@host=http://localhost:8084
@clientid=acme
@clientsecret=acmesecret
@redirect_uri=http://jyj.tjhx.gov.cn
@user=admin
@password=123456

## 授权模式
### 授权码 Authorization Code

###发起请求
GET {{host}}/oauth/authorize?response_type=code&client_id={{clientid}}&client_secret={{clientsecret}}&redirect_uri={{redirect_uri}}

###换取令牌
POST {{host}}/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{clientid}} {{clientsecret}}

grant_type=authorization_code&redirect_uri={{redirect_uri}}&code=0y1akY


### 隐式许可 Implicit
## 发起请求
GET {{host}}/oauth/authorize?response_type=token&client_id={{clientid}}&client_secret={{clientsecret}}&redirect_uri={{redirect_uri}}


### 资源所有者密码凭证 Resource Owner Password Credentials
Not support


### 客户端凭证 Client Credentials
### 请求客户端令牌
POST {{host}}/oauth/token
Authorization: Basic {{clientid}} {{clientsecret}}
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials


####

GET {{host}}/custoken


### 验证令牌

@token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyYzlkMDA4MTY4MjEyN2I3MDE2ODIxMzcyYzA3MDAwMCIsInVzZXJfbmFtZSI6IjJjOWQwMDgxNjgyMTI3YjcwMTY4MjEzNzJjMDcwMDAwIiwic2NvcGUiOlsiYXV0aCIsInByb2ZpbGUiXSwiZXhwIjoxNTY4NDM0MzA1LCJhdXRob3JpdGllcyI6WyJST0xFX0FOWU9ORSJdLCJqdGkiOiI4ODhjZGM1MC1lNThmLTQxZDItYjU3Yi02MzdlMWMzZDczZjYiLCJjbGllbnRfaWQiOiJhY21lIn0.Cmm3MFDscWCDG0VfaxHHtf7XB0i1gqW6HsH6qVjXO0iVYB7Zdw9ww1u35BD0JQTkJdv5lQbwaIvCpCsZaf9Tsh5ZZNxb63srgu2xV44tLXNSRKeFbAFehtICKHFTV5IpB17IjhkiLwdO09v0SVTuTMeP2I4MU2zj-yvbgkYve4oyfcrpL6jXSqIaobgG6B1wLXTpppM-EKfeLkCyh0ArsyLlUiBN9alC2x_0XhFFQbuwIpQJIzB6pf5qaqoo_ot-7EnLl1pWpm1pYC7oNGUzIzmGADmnya9IiMfywIREDE_vgs8UrJyCuAV7nL92w4HFsMGh200kSoB75MQIRjnNvg

GET {{host}}/oauth/check_token?token={{token}}
Authorization: Bearer {{token}}


### XTOKEN 认证
GET {{host}}/pro
Authorization: XTOKEN Godotot

### 
GET {{host}}/pro?client_id={{clientid}}
Authorization: Bearer {{token}}

### by usernanme
POST {{host}}/auth/login
Content-Type: application/json

{"username":"{{user}}", "password": "{{password}}"}



### XTOKEN 认证
GET http://localhost:8088/userinfo
Authorization: Bearer {{token}}


####
GET {{host}}/.well-known/jwks