@host=localhost:8084
@username=admin
@userpwd=123456
@clientid=acme
@clientsecret=acmesecret
@redirect_uri=http://jyj.tjhx.gov.cn
@token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyYzlkMDA4MTY4MjEyN2I3MDE2ODIxMzcyYzA3MDAwMCIsInVzZXJfbmFtZSI6IjJjOWQwMDgxNjgyMTI3YjcwMTY4MjEzNzJjMDcwMDAwIiwic2NvcGUiOlsib3BlbmlkIl0sImV4cCI6MTU1NzY4ODExOSwiYXV0aG9yaXRpZXMiOlsiUk9MRV9BTllPTkUiXSwianRpIjoiNjc3ZmIxMDEtZTA4My00MWZlLThiNjYtM2Y5NzU5MGYxYTI3IiwiY2xpZW50X2lkIjoiYWNtZSJ9.ca20ce5AedxLeF1vTWYl4SezdhRnF8OeipDXR_ZGI3bXpqgKi2eR-lySWEh9BSPIQ8QoYcpORovJjGKyoVVx5g_W4-XdB3lETIgao9KND_2D-SsUjjyhljNmYU9RSLpaZ2O2IA-zU_Ys2YigPBy3AcwcsrDY371BLgdbVgcv8eUA1w8fTg05xCDNTztS-lmqO4KIbiqZup11EBsUdrxbCwb5LKSRsM5GW-cHg-9qzfuetODGfz-vXHc_M1zsYonD6G4iWH2KAaS7hvJ6onZNHtwwAsJQRU4czfqg22TGAilNAXwjSBeLErLd5KQPCJMp5H-JBoOK2d6XBW5biIcxAA

## 登录
GET http://{{host}}/login

GET http://{{host}}/logout

POST http://{{host}}/login
Content-Type: application/x-www-form-urlencoded

username=admin&password=123456&_csrf=fffc871e-0aa6-4c25-8363-abd948654b35



## 授权码模式(code)
# step1
GET http://{{host}}/oauth/authorize
    ?response_type=code&client_id={{clientid}}&client_secret={{clientsecret}}
    &redirect_uri={{redirect_uri}}&scope=openid

# step2
GET http://{{host}}/login
Cookie: JSESSIONID=5BCF5276C095FC4235D0E9A276410BFB

#step3
POST http://{{host}}/login
Content-Type: application/x-www-form-urlencoded

username={{username}}&password={{userpwd}}&_csrf=29888314-61fc-45a5-b1b7-c20234315566

#step4
POST http://{{host}}/oauth/authorize
Content-Type: application/x-www-form-urlencoded

_csrf=13b74ac1-cee4-4e78-83ab-884b1fc5c020&user_oauth_approval=true&scope.openid=true

#step5 
POST http://{{host}}/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic acme acmesecret

grant_type=authorization_code&redirect_uri={{redirect_uri}}&code=MkU9ex


# {
#   "access_token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NTY4MzY5MjQsInVzZXJfbmFtZSI6ImFkbWluIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9BTllPTkUiXSwianRpIjoiN2YyYjIwYjQtYzM2ZS00MDhjLTgwZTctNWQ4MjY0ZTRmMGE1IiwiY2xpZW50X2lkIjoiYWNtZSIsInNjb3BlIjpbIm9wZW5pZCJdfQ.VydBJmEgyGlCf4Lc-kBCLBdnVDGRfHwbdiakY-oy6t1nHWWJEsNiqj2Kh7GYBRQQ2eu-5B6soNS-Ur0gWYNqYUWJIX28YboSWBqYF1LIIcr-eBIWDlxH7MbhtBmnJC-tNYWcaEtX-FOmnoT1I2nLZNNWGu7pNqfpnQoDPMAc_uni0cGaTn-cJB00siQ0bMaD5Qf-TFQ5WzDvNAT0Y7cmY3t0nmao2BCz5WyawvyW4PIaTy-aZA7ESqv5xLtuK0xU2jGDeFVVNSuI5OJWrtaDmgDiAqqxjVua5D6DnVnFhjXE3OmgFCnwAKvjymQ8fdloFF5FdQKnyynLFiqbaEue2A",
#   "token_type": "bearer",
#   "refresh_token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJhZG1pbiIsInNjb3BlIjpbIm9wZW5pZCJdLCJhdGkiOiI3ZjJiMjBiNC1jMzZlLTQwOGMtODBlNy01ZDgyNjRlNGYwYTUiLCJleHAiOjE1NTkzODU3MjQsImF1dGhvcml0aWVzIjpbIlJPTEVfQU5ZT05FIl0sImp0aSI6ImM0Y2E2OWE0LTcyMTktNDI4Ny04ZTEwLWNmOTM1YWQwNjYwNCIsImNsaWVudF9pZCI6ImFjbWUifQ.B-jYNxWx8XfXDIfc8bqCrK0nYiFDZSvQioelgHPhgkRmTcvCkCk3o_2kzYxIJZGEIr5qtSc6Jvy1raHlE97aViIPhJYJi74RG1qX_Lqt0TOf0pfwitKtvJQC3Ycm7chu3G7kn57-8kXHHQAMl5HxXIC3hfYFcBuA2XTKPuqpP8J9kMILLt8HbuwMzAk-7o_QoZ9Idl6DKeOnvoypwwS63Xnq3FNIwfOuSJGFsBbOndoQJRuXuH_Y-IeKaizFBDQmUvEwuaHNVaTs1GuO-kVgCQxPDfGImncrpT3FfftYhOCrrWNUxHqami2Nbel5JMpYb95_X4DSg6R7njirkzkFQg",
#   "expires_in": 43199,
#   "scope": "openid",
#   "jti": "7f2b20b4-c36e-408c-80e7-5d8264e4f0a5"
# }

## 简化模式（implicit grant type）
# step 1
GET http://{{host}}/oauth/authorize
    ?response_type=token&client_id={{clientid}}&client_secret={{clientsecret}}
    &redirect_uri={{redirect_uri}}&scope=openid



# step 4
POST http://{{host}}/oauth/authorize
Content-Type: application/x-www-form-urlencoded

_csrf=29888314-61fc-45a5-b1b7-c20234315566&user_oauth_approval=true


http://jyj.tjhx.gov.cn#access_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NTY4MzczNDMsInVzZXJfbmFtZSI6ImFkbWluIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9BTllPTkUiXSwianRpIjoiYTFmY2ZiNTUtZmE3OC00ZTYwLTk4N2YtYmQzODVjNDUxOTllIiwiY2xpZW50X2lkIjoiYWNtZSIsInNjb3BlIjpbIm9wZW5pZCJdfQ.Wz_jL9pkBs9PFPsnweFFcRxQPvh3Tv-VPMTrDnhegjftO3MIp_spk-YKDA8yNT-hRaVWkZu3Mri8NIZMvkOIzmOGgIGsDKAnrnqTbF6yl6lUW-dvLO4NHyGLK6kQdY_I7OycNW2kSlL6t8XtSU1iKRSZNlKqrrFMWtrbz2Yo-Zym3lapLOYPZcP20JKQ_tM6omrYtamZ7mkVZMxTkidEO9hWMc6QYB-yAWDbTiSpLYHEKGxa_gJc3mrYvHwAoQ7GJmTa3eYroB4YrT_zvQEXvvbX19sch8COXydIFJgqLL7iTRCN7-rarDBT4y9WtQc6YkNY5Nc-xsuS9JfthshoIA&token_type=bearer&expires_in=38984&jti=a1fcfb55-fa78-4e60-987f-bd385c45199e
## 密码模式（Resource Owner Password Credentials Grant） not support
POST http://{{host}}/oauth/token?client_id={{clientid}}&client_secret={{clientsecret}}
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=admin&password=123456


## 客户端模式 
POST http://{{host}}/oauth/token
Authorization: Basic acme acmesecret
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials


#=================================
## 更新令牌
POST http://{{host}}/oauth/token
Authorization: Basic {{clientid}} {{clientsecret}}
Content-Type: application/x-www-form-urlencoded

grant_type=refresh_token&refresh_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJhZG1pbiIsInNjb3BlIjpbIm9wZW5pZCJdLCJhdGkiOiI3ZjJiMjBiNC1jMzZlLTQwOGMtODBlNy01ZDgyNjRlNGYwYTUiLCJleHAiOjE1NTkzODU3MjQsImF1dGhvcml0aWVzIjpbIlJPTEVfQU5ZT05FIl0sImp0aSI6ImM0Y2E2OWE0LTcyMTktNDI4Ny04ZTEwLWNmOTM1YWQwNjYwNCIsImNsaWVudF9pZCI6ImFjbWUifQ.B-jYNxWx8XfXDIfc8bqCrK0nYiFDZSvQioelgHPhgkRmTcvCkCk3o_2kzYxIJZGEIr5qtSc6Jvy1raHlE97aViIPhJYJi74RG1qX_Lqt0TOf0pfwitKtvJQC3Ycm7chu3G7kn57-8kXHHQAMl5HxXIC3hfYFcBuA2XTKPuqpP8J9kMILLt8HbuwMzAk-7o_QoZ9Idl6DKeOnvoypwwS63Xnq3FNIwfOuSJGFsBbOndoQJRuXuH_Y-IeKaizFBDQmUvEwuaHNVaTs1GuO-kVgCQxPDfGImncrpT3FfftYhOCrrWNUxHqami2Nbel5JMpYb95_X4DSg6R7njirkzkFQg


GET  http://{{host}}/oauth/check_token?token={{token}}
Authorization: Basic {{clientid}} {{clientsecret}}
Content-Type: application/x-www-form-urlencoded


GET http://{{host}}/oauth/token_key
Authorization: Basic acme acmesecret
Content-Type: application/x-www-form-urlencoded



GET http://{{host}}/userinfo
Authorization: bearer {{token}}
Content-Type: application/x-www-form-urlencoded



GET http://localhost:8088/userinfo
Authorization: Bearer {{token}}
Content-Type: application/x-www-form-urlencoded 





GET http://localhost:8080/starter/userinfo
Authorization: Bearer {{token}}
Content-Type: application/x-www-form-urlencoded 

GET http://localhost:8080/qst/F
Authorization: bearer {{token}}
Content-Type: application/x-www-form-urlencoded 

http://localhost:8082/sayHello?name=fff



http://localhost:8080/sd/sayHello?name=fff
Content-Type: application/x-www-form-urlencoded 
Authorization: Bearer {{token}}



http://localhost:8080/authz-server/login

POST http://{{host}}/authz-server/login
Content-Type: application/x-www-form-urlencoded

username={{username}}&password={{userpwd}}&_csrf=29888314-61fc-45a5-b1b7-c20234315566

GET http://localhost:8080/authz-server/oauth/authorize
    ?response_type=token&client_id={{clientid}}&client_secret={{clientsecret}}
    &redirect_uri={{redirect_uri}}&scope=openid

POST http://localhost:8080/authz-server/oauth/authorize
Content-Type: application/x-www-form-urlencoded

_csrf=13b74ac1-cee4-4e78-83ab-884b1fc5c020&user_oauth_approval=true&scope.openid=true


POST http://{{host}}/authz-server/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic acme acmesecret

grant_type=authorization_code&redirect_uri={{redirect_uri}}&code=oZeB9Q





http://localhost:8080/authz-server/oauth/authorize?response_type=token&client_id=acme&client_secret=acmesecret&scope=openid&redirect_uri=http://jyj.tjhx.gov.cn