server:
  port: 8082
spring:
  application:
    name: example-server
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8084/.well-known/jwks
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka