spring:
  application:
    name: thallo_gateway_server
  cloud:
    gateway:
      routes:
        - id: hello_route
          uri: lb://example-server
          predicates:
            - Path=/service/{segment}
          filters:
            - SetPath=/{segment}
        - id: 163_route
          uri: lb://simple-client1
          predicates:
            - Path=/qst/{segment}
          filters:
            - SetPath=/{segment}
security:
    oauth2:
        client:
            clientId: acme
            clientSecret: acmesecret
            accessTokenUri: http://localhost:8084/uaa/oauth/access_token
            userAuthorizationUri: http://localhost:8084/uaa/oauth/authorize
            clientAuthenticationScheme: form
        resource:
          user-info-uri:  'http://localhost:8084/uaa/oauth/authorize'
          token-info-uri: 'http://localhost:8084/uaa/oauth/check_token'
