###########################################################
## doc: https://cloud.spring.io/spring-cloud-static/spring-cloud-gateway/2.1.0.RELEASE/single/spring-cloud-gateway.html#gateway-how-it-works
###########################################################

spring:
  application:
    name: gateway-server
  security:
    oauth2:
      client:
        registration:
          sso:
            provider: thallo
            client-id: acme
            client-secret: acmesecret
            authorization-grant-type: authorization_code
#            redirect-uri-template: "{baseUrl}/oauth2/callback/{registrationId}"
            redirect-uri-template: "http://localhost:8080/thallo-starter/userinfo"
            scope: auth
        provider:
          thallo:
            authorization-uri: http://localhost:8084/oauth/authorize
            token-uri: http://localhost:8084/oauth/token
            user-info-uri: http://localhost:8084/oauth/userinfo
#            token-info-uri: http://localhost:8084/oauth/check_token
#            user-name-attribute: sub
#            jwk-set-uri: http://localhost:8084/.well-known/jwks
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8084/.well-known/jwks
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      discovery:
        locator:
          enabled: true
      routes:
        - id: thallo-starter
          uri: http://localhost:8088
          predicates:
            - Path=/thallo-starter/**
          filters:
            - StripPrefix=1
            - TokenRelay=

        - id: example-server
          uri: lb://example-server
          predicates:
          - Path=/example-server/**
          filters:
          - StripPrefix=1
          - TokenRelay=

        - id: example-server-http
          uri: http://localhost:8082
          predicates:
          - Path=/example-server-htp/**
          filters:
          - StripPrefix=1
          - TokenRelay=

#example-server-r:
#  ribbon:
#    listOfServers: localhost:8082
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.thalo: 'DEBUG'
    org.springframework: 'DEBUG'