spring:
  application:
    name: gateway-server
  security:
    oauth2:
      client:
        registration:
          sso:
            provider: uaa
            client-id: acme5
            client-secret: acmesecret5
            authorization-grant-type: authorization_code
            redirect-uri-template: "{baseUrl}/login/oauth2/callback/{registrationId}"
            scope: openid
        provider:
          uaa:
            authorization-uri: http://localhost:8084/oauth/authorize
            token-uri: http://localhost:8084/oauth/token
#            user-info-uri: http://localhost:8084/oauth/userinfo
#            token-info-uri: http://localhost:8084/oauth/check_token
#            user-name-attribute: sub
            jwk-set-uri: http://localhost:8084/.well-known/jwks
#      resourceserver:
#        jwt:
#          jwk-set-uri: http://localhost:8084/.well-known/jwks
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://docs.spring.io"
              - "http://baidu.com"
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      discovery:
        locator:
          enabled: true
      routes:
        - id: 163_route
          uri: https://www.163.com
          predicates:
            - Path=/qst/{segment}
          filters:
            - SetPath=/{segment}
        - id: starter-service
          uri: http://localhost:8088
          predicates:
            - Path=/starter/**
          filters:
            - StripPrefix=1
            - TokenRelay=
        - id: authz-server
          uri: http://localhost:8084
          predicates:
          - Path=/authz-server/**
          filters:
          - StripPrefix=1
        - id: serverside-service
          uri: http://localhost:8082
          predicates:
          - Path=/sd/**
          filters:
          - StripPrefix=1
          - TokenRelay=

logging:
  level:
    org.thalo: 'DEBUG'
    org.springframework: 'DEBUG'