server:
  port: 8084

spring:
  application:
    name: authz_server
  datasource:
    url: 'jdbc:mysql://localhost:3306/identity_v2?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false'
    username: 'root'
    password: 'root'
    driverClassName: 'com.mysql.cj.jdbc.Driver'
  redis:
    host: 127.0.0.1
    port: 6379
    # password: password

security:
  user:
    password: 'password'
  ignored: '/css/**,/js/**,/favicon.ico,/webjars/**'

logging:
  level:
    org:
      thalo: 'DEBUG'
      springframework:
        security: 'DEBUG'


thallo:
  authzserver:
    security:
      oauth2:
        clients:
          ## 开启内存中存放oauth2 client信息，方便开发环境测试
          memory-clients-enabled: true
          jdbc-clients-enabled: true
          client-details:
            - client-id: acme
              client-secret: '{noop}acmesecret'
              redirect-uri:
                - http://jyj.tjhx.gov.cn
              authorizedGrantTypes:
                - authorization_code
                - refresh_token
                - implicit
                - client_credentials
              scopes:
                - openid