spring:
  application:
    name: auth_server

server:
  contextPath: '/uaa'

security:
  user:
    password: 'password'
  ignored: '/css/**,/js/**,/favicon.ico,/webjars/**'

logging:
  level:
    org:
      springframework:
        security: 'DEBUG'