spring:
  application:
    name: auth_server
  data:
    mongodb:
      uri: 'mongodb://localhost/userdb'

server:
  port: 8084

security:
  user:
    password: 'password'
  ignored: '/css/**,/js/**,/favicon.ico,/webjars/**'


logging:
  level:
    org:
      springframework:
        security: 'DEBUG'