server:
  port: 8084

spring:
  application:
    name: thallo_auth_server
  datasource:
    url: 'jdbc:mysql://localhost:3306/identity_v2?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false'
    username: 'root'
    password: 'root'
    driverClassName: 'com.mysql.cj.jdbc.Driver'

security:
  user:
    password: 'password'
  ignored: '/css/**,/js/**,/favicon.ico,/webjars/**'

logging:
  level:
    org:
      springframework:
        security: 'DEBUG'