thallo:
  authzserver:
    oauth2:
      clients:
        jdbc-clients-enabled: true
        ## 开启内存中存放oauth2 client信息，方便开发环境测试
        memory-clients-enabled: true
        client-details:
          - client-id: acme
            client-secret: '{noop}acmesecret'
            redirect-uri:
              - http://jyj.tjhx.gov.cn
              - http://127.0.0.1:51070
            authorizedGrantTypes:
              - authorization_code
              - refresh_token
              - implicit
              - client_credentials
              - password
            scopes:
              - auth
              - profile
    security:
      resources:
        - /.well-known/jwks
        - /custoken
        - /logins

security:
  oauth2:
    authorization:
      realm: thallo-oauth2
      jwt:
        key-store: classpath:/keystore.jks
        key-store-password: password
        key-alias: oauth2