spring:
  thymeleaf:
    cache: false
  devtools:
    restart:
      additional-paths:
        - /templates/**
        - classpath*:/templates/**

logging:
  level:
    com.springboot: trace
    org.springframework.cloud: trace
    com.springboot.cloud: trace
    com.jalja.org.spring: debug
    redis.clients: trace