server:
  port: 8088

spring:
  application:
    name: thallo-starter
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8084/.well-known/jwks

management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  hystrix:
    enabled: true

ribbon:
  OkToRetryOnAllOperations: false

hystrix:
  command:
    serverMethod:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
logging:
  level:
    org:
      thalo: DEBUG
#      springframework: DEBUG