@host=http://127.0.0.1:8080


######################
POST {{host}}/gateway/routes
Content-Type: application/json

{
    "routeId": "test",
    "uri": "https://www.baidu.com",
    "predicates": "[  {\"name\":\"Path\", \"args\": {\"patterns\":\"/mytest/**\"}}]",
    "filters": "[{\"name\":\"StripPrefix\", \"args\": {\"parts\":1}}]",
    "description": "测试环境"
}

### 
PUT {{host}}/gateway/routes/8a7eb25c7139e1e001713a081b0a0016
Content-Type: application/json

{
    "routeId": "test",
    "uri": "https://www.baidu.com",
    "predicates": "[  {\"name\":\"Path\", \"args\": {\"patterns\":\"/mytest/**\"}}]",
    "filters": "[{\"name\":\"StripPrefix\", \"args\": {\"parts\":1}}]",
    "description": "测试环境"
}


###
POST {{host}}/gateway/routes
Content-Type: application/json

{
    "routeId": "payable_api",
    "uri": "http://payable.zemutec.com/",
    "predicates": "[  {\"name\":\"Path\", \"args\": {\"patterns\":\"/payable/**\"}}]",
    "filters": "[{\"name\":\"StripPrefix\", \"args\": {\"parts\":1}}]",
    "description": "测试环境"
}

8a7eb25c713a833d01713da5cde30000

###
GET {{host}}/actuator/gateway/globalfilters

####
POST {{host}}/payable/backend/identity/login
Content-Type: application/json

{
    "account": "15902347086",
    "password": "123456",
    "authType": "P"
}


####
GET http://localhost:8080/mytest

####
GET http://localhost:8080/actuator/health
####
OPTIONS    http://localhost:8080/mytest
Access-Control-Request-Method: BATC
Host: api.alice.com
Connection: keep-alive

# {
# name: "Path",
# args: {
#     "Path": "/path"
# }
# }